#!/bin/sh
cd "$(dirname "$0")"
export LD_LIBRARY_PATH="/system/lib64:$LD_LIBRARY_PATH"
if [ -f /EON ]; then
  export LD_LIBRARY_PATH="../../third_party/mapbox-gl-native-qt/x86_64:$LD_LIBRARY_PATH"
fi
export QT_PLUGIN_PATH="../../third_party/qt-plugins/$(uname -m)"
exec ./_ui
